export const greetings = {
  questions: {
    "greetings.bye": [
      "goodbye for now",
      "bye bye take care",
      "okay see you later",
      "bye for now",
      "i must go",
      "goodbye",
      "bye",
      "see you",
      "see you later",
      "see you soon",
      "take care",
      "farewell",
      "so long",
      "until next time",
      "until we meet again",
      "catch you later",
      "later",
      "laters",
      "peace",
      "peace out",
      "toodles",
      "toodle-oo",
      "toodle-pip",
      "toodle-loo",
    ],
    "greetings.hello": [
      "hello",
      "hi",
      "howdy",
      "hey",
      "greetings",
      "good day",
      "good morning",
      "good afternoon",
      "good evening",
      "good night",
      "good to see you",
      "nice to see you",
      "nice to meet you",
      "pleased to meet you",
      "how are you",
      "how is it going",
      "how is everything",
      "how are things",
      "how are you doing",
      "how is life",
      "how is your day",
      "how is your day going",
      "how is your day been",
      "how is your day been going",
      "how is your day been so far",
      "how is your day been so far",
      "how is your day been so far today",
    ],
  },
  answers: {
    "greetings.bye": [
      "Till next time",
      "see you soon!",
      "goodbye!",
      "bye!",
      "bye bye!",
      "see you later!",
      "see you soon!",
      "take care!",
      "farewell!",
      "so long!",
      "until next time!",
      "until we meet again!",
      "catch you later!",
      "later!",
      "laters!",
      "peace!",
      "peace out!",
      "toodles!",
      "toodle-oo!",
      "toodle-pip!",
      "toodle-loo!",
    ],
    "greetings.hello": [
      "Hey there!",
      "Greetings!",
      "Hello!",
      "Hi!",
      "Hai there!",
      "Hai",
      "Howdy!",
      "Good day!",
      "Good to see you!",
      "Nice to see you!",
      "Nice to meet you!",
      "Pleased to meet you!",
      "How are you!",
      "How is it going!",
      "How is everything!",
      "How are things!",
      "How are you doing!",
      "How is life!",
      "How is your day!",
      "How is your day going!",
      "How is your day been!",
      "How is your day been going!",
      "How is your day been so far!",
      "How is your day been so far!",
      "How is your day been so far today!",
      "How is your day been so far today!",
    ],
  },
};
