export const greetings = {
  questions: {
    // ===== GREETINGS =====
    "greetings.bye": [
      "goodbye for now",
      "bye bye take care",
      "okay see you later",
      "bye for now",
      "i must go",
      "goodbye",
      "bye",
      "see you",
      "see you later",
      "see you soon",
      "take care",
      "farewell",
      "so long",
      "until next time",
      "until we meet again",
      "catch you later",
      "later",
      "laters",
      "peace",
      "peace out",
      "toodles",
    ],
    "greetings.hello": [
      "hello",
      "hi",
      "howdy",
      "hey",
      "greetings",
      "good day",
      "good morning",
      "good afternoon",
      "good evening",
      "good night",
      "good to see you",
      "nice to see you",
      "nice to meet you",
      "pleased to meet you",
      "how are you",
      "how is it going",
      "how is everything",
      "how are things",
      "how are you doing",
      "how is life",
      "how is your day",
      "what's up",
      "wassup",
      "hey there",
      "yo",
    ],

    // ===== SERVICES =====
    "services.mobile": [
      "do you offer mobile app development",
      "can you build an ios app",
      "can you create an android app",
      "mobile app development services",
      "what mobile services do you provide",
      "do you develop for ios and android",
      "can you help with app development",
      "mobile application development",
      "ios app development",
      "android app development",
      "native app development",
      "cross platform app development",
      "what are your mobile services",
      "flutter development",
      "react native development",
      "swift development",
      "kotlin development",
      "mobile game development",
      "app porting services",
    ],
    "services.web": [
      "do you offer web development",
      "can you build a website",
      "web design services",
      "web development",
      "website creation",
      "do you do web design",
      "can you create a website",
      "web application development",
      "custom web development",
      "responsive website design",
      "what web services do you offer",
      "full stack development",
      "frontend development",
      "backend development",
      "mern stack",
      "mean stack",
      "next.js development",
      "vue.js development",
      "angular development",
      "e-commerce website",
      "saas development",
      "web app development",
    ],
    "services.ai": [
      "do you offer ai services",
      "can you implement machine learning",
      "do you work with artificial intelligence",
      "ai development",
      "machine learning services",
      "what ai solutions do you provide",
      "can you build ai models",
      "data science services",
      "neural networks",
      "natural language processing",
      "computer vision",
      "deep learning",
      "predictive analytics",
      "chatbot development",
      "recommendation systems",
      "image recognition",
      "text analysis",
      "data mining",
      "ai consulting",
    ],
    "services.blockchain": [
      "do you offer blockchain services",
      "can you develop blockchain solutions",
      "cryptocurrency development",
      "smart contract development",
      "web3 development",
      "do you work with blockchain",
      "blockchain consulting",
      "decentralized application development",
      "dapp development",
      "nft development",
      "defi development",
      "ethereum development",
      "solidity programming",
      "cryptocurrency wallet",
      "token development",
      "blockchain integration",
      "blockchain audit",
    ],
    "services.security": [
      "do you offer cybersecurity services",
      "can you help with security",
      "penetration testing",
      "security consulting",
      "what security services do you provide",
      "do you do security audits",
      "vulnerability assessment",
      "secure application development",
      "data protection",
      "compliance services",
      "security training",
      "incident response",
      "network security",
      "application security",
      "code review",
      "security testing",
      "encryption services",
      "data security",
    ],
    "services.design": [
      "do you offer design services",
      "can you design my interface",
      "ui ux design",
      "graphic design",
      "what design services do you provide",
      "do you do user experience design",
      "can you help with product design",
      "branding services",
      "wireframing",
      "prototyping",
      "logo design",
      "brand identity",
      "web design",
      "app interface design",
      "user research",
      "design system",
      "animation design",
      "mockup creation",
    ],

    // ===== PRICING & QUOTES =====
    "pricing.inquiry": [
      "how much does development cost",
      "what is your pricing",
      "how do you charge",
      "what are your rates",
      "can you give me a quote",
      "how much for a project",
      "pricing information",
      "cost of development",
      "project estimation",
      "how do you calculate costs",
      "are you affordable",
      "budget options",
      "payment plans",
      "pricing models",
      "cost breakdown",
    ],
    "pricing.free_trial": [
      "do you offer a free trial",
      "is there a trial period",
      "can i try before buying",
      "do you have a free plan",
      "free trial available",
      "demo available",
      "free consultation",
      "sample project",
    ],

    // ===== COMPANY INFO =====
    "company.info": [
      "who are you",
      "tell me about codenuity",
      "what does codenuity do",
      "what is codenuity solutions",
      "about your company",
      "what services do you offer",
      "what does your company do",
      "who is your team",
      "company background",
      "company overview",
      "company story",
      "mission statement",
      "company values",
      "company vision",
    ],
    "company.team": [
      "who is your team",
      "tell me about your team",
      "how many people work there",
      "team size",
      "your company size",
      "team expertise",
      "team experience",
      "who are the founders",
      "team members",
      "leadership team",
    ],
    "company.experience": [
      "how long have you been in business",
      "years of experience",
      "company history",
      "since when are you operating",
      "when did you start",
      "experience in the industry",
      "how experienced are you",
      "track record",
    ],

    // ===== CONTACT & LOCATION =====
    "contact.information": [
      "how can i contact you",
      "what is your contact information",
      "how do i reach you",
      "what is your phone number",
      "what is your email",
      "where are you located",
      "what is your address",
      "how to get in touch",
      "contact details",
      "office location",
      "contact us",
      "reach out to us",
    ],
    "contact.support": [
      "how can i get support",
      "technical support",
      "customer support",
      "support available",
      "help needed",
      "i need assistance",
      "can you help me",
    ],

    // ===== TIMELINE & DELIVERY =====
    "timeline.inquiry": [
      "how long does a project take",
      "what is the timeline",
      "how many days to complete",
      "project duration",
      "how much time do you need",
      "development timeline",
      "when can you start",
      "project schedule",
      "delivery timeframe",
      "how fast can you deliver",
      "turnaround time",
      "estimated completion",
    ],
    "timeline.urgent": [
      "i need it urgently",
      "can you do it fast",
      "urgent project",
      "expedited delivery",
      "rush job",
      "short deadline",
      "how soon can you start",
      "asap needed",
    ],

    // ===== CASE STUDIES & PORTFOLIO =====
    "portfolio.casestudies": [
      "show me case studies",
      "do you have portfolio",
      "previous projects",
      "past work",
      "client projects",
      "example projects",
      "show your work",
      "success stories",
      "case study examples",
      "client testimonials",
    ],
    "portfolio.similar": [
      "have you done similar projects",
      "do you have experience with this",
      "have you worked on this before",
      "similar project experience",
      "past similar work",
      "reference projects",
    ],

    // ===== PARTNERSHIPS & COLLABORATION =====
    "partnership.inquiry": [
      "can we partner with you",
      "partnership opportunities",
      "collaboration",
      "work together",
      "business partnership",
      "partnership proposal",
      "reseller program",
      "affiliate program",
      "licensing options",
    ],

    // ===== PROCESS & METHODOLOGY =====
    "process.workflow": [
      "what is your development process",
      "how do you work",
      "project workflow",
      "development methodology",
      "agile process",
      "how do you handle projects",
      "project phases",
      "working style",
    ],
    "process.communication": [
      "how do you communicate",
      "project updates",
      "progress reports",
      "communication frequency",
      "status updates",
      "how often do i hear from you",
    ],
    "process.revision": [
      "do you include revisions",
      "revision policy",
      "unlimited revisions",
      "how many revisions",
      "change requests",
      "modification process",
    ],

    // ===== TECHNOLOGY & STACK =====
    "tech.stack": [
      "what technology do you use",
      "what tech stack",
      "do you use react",
      "programming languages",
      "backend technologies",
      "database options",
      "hosting solutions",
      "deployment options",
      "frameworks used",
    ],
    "tech.scalability": [
      "can it scale",
      "scalability",
      "high traffic handling",
      "performance optimization",
      "load balancing",
      "cloud infrastructure",
    ],

    // ===== MAINTENANCE & SUPPORT =====
    "maintenance.support": [
      "do you provide maintenance",
      "post launch support",
      "ongoing support",
      "maintenance plan",
      "support package",
      "bug fixes",
      "updates and patches",
      "technical support duration",
    ],
    "maintenance.hosting": [
      "do you host the application",
      "hosting included",
      "server management",
      "infrastructure management",
      "deployment included",
      "devops support",
    ],

    // ===== TRAINING & DOCUMENTATION =====
    "training.needed": [
      "do you provide training",
      "user training",
      "team training",
      "documentation provided",
      "knowledge transfer",
      "onboarding process",
      "learning materials",
    ],

    // ===== CUSTOMIZATION & FLEXIBILITY =====
    "custom.requirements": [
      "can you customize for us",
      "custom development",
      "tailored solution",
      "specific requirements",
      "unique needs",
      "custom features",
      "can you build custom",
    ],

    // ===== PAYMENT & TERMS =====
    "payment.methods": [
      "what payment methods",
      "payment options",
      "do you accept",
      "invoice terms",
      "payment schedule",
      "deposit required",
      "payment milestones",
    ],

    // ===== LEGAL & COMPLIANCE =====
    "legal.terms": [
      "what are your terms",
      "terms and conditions",
      "privacy policy",
      "nda available",
      "legal agreement",
      "contract terms",
      "liability",
    ],
    "legal.compliance": [
      "gdpr compliant",
      "data protection",
      "compliance standards",
      "certifications",
      "security compliance",
      "industry standards",
    ],

    // ===== JOBS & CAREERS =====
    "jobs.inquiry": [
      "are you hiring",
      "job opportunities",
      "career with you",
      "open positions",
      "employment",
      "internship opportunities",
      "we want to join",
    ],

    // ===== COMMON QUESTIONS =====
    "faq.difference": [
      "what makes you different",
      "why choose you",
      "your competitive advantage",
      "what sets you apart",
      "unique selling points",
      "why should i choose you",
    ],
    "faq.quality": [
      "how do you ensure quality",
      "quality assurance",
      "testing process",
      "quality standards",
      "quality metrics",
      "code quality",
      "best practices",
    ],
    "faq.guarantee": [
      "do you guarantee",
      "money back guarantee",
      "satisfaction guarantee",
      "warranty",
      "guarantees offered",
    ],
  },

  answers: {
    // GREETINGS
    "greetings.bye": [
      "Till next time!",
      "See you soon!",
      "Goodbye!",
      "Bye! Have a great day!",
      "Take care!",
      "Farewell!",
      "See you later!",
      "Catch you next time!",
    ],
    "greetings.hello": [
      "Hey there! Welcome to Codenuity Solutions!",
      "Greetings! How can I assist you today?",
      "Hello! Great to see you. What can I help with?",
      "Hi! I'm here to answer any questions about our services.",
      "Howdy! What brings you here today?",
      "Good day! How can we help you?",
      "Welcome! I'm happy to help.",
      "Hi there! What would you like to know?",
    ],

    // SERVICES
    "services.mobile": [
      "Yes! We specialize in mobile app development for both iOS and Android platforms. We create native and cross-platform applications tailored to your business needs.",
      "Absolutely! We offer comprehensive mobile app development services including iOS, Android, React Native, and Flutter.",
      "We do! Our experienced mobile development team builds high-quality apps using modern technologies.",
    ],
    "services.web": [
      "Yes! We provide full-stack web development using React, Next.js, Vue.js, and other modern frameworks.",
      "Definitely! Our web development team builds responsive, scalable web applications and e-commerce platforms.",
      "We do! We specialize in custom web development, frontend and backend solutions.",
    ],
    "services.ai": [
      "Yes! We offer AI and machine learning services including custom models, NLP, computer vision, and predictive analytics.",
      "Absolutely! Our AI team can develop chatbots, recommendation systems, and intelligent automation solutions.",
      "We do! We specialize in AI/ML implementations that solve real business problems.",
    ],
    "services.blockchain": [
      "Yes! We provide blockchain services including smart contracts, DApps, NFTs, and cryptocurrency solutions.",
      "Definitely! Our blockchain team offers web3 development, token creation, and blockchain consulting.",
      "We do! We offer comprehensive blockchain development services for various use cases.",
    ],
    "services.security": [
      "Absolutely! We provide cybersecurity services including penetration testing, security audits, and vulnerability assessments.",
      "Yes! We offer comprehensive security solutions to protect your applications and data.",
      "We do! Our security experts help identify and fix vulnerabilities.",
    ],
    "services.design": [
      "Yes! We offer UI/UX design, graphic design, branding, wireframing, and prototyping services.",
      "Absolutely! Our design team creates beautiful and functional user experiences.",
      "We do! We specialize in user-centered design that's both beautiful and intuitive.",
    ],

    // PRICING
    "pricing.inquiry": [
      "Project costs vary based on scope and complexity. We provide custom quotes after understanding your requirements.",
      "We offer flexible pricing models. Share your project details, and we'll provide a detailed estimate.",
      "Our pricing depends on your specific needs. Contact us with your requirements for an accurate quote.",
    ],
    "pricing.free_trial": [
      "Yes! We offer free consultations to discuss your project and provide pricing.",
      "Absolutely! We're happy to have an initial conversation about your project.",
      "We provide free consultations to help you understand project costs.",
    ],

    // COMPANY
    "company.info": [
      "Codenuity Solutions is a leading technology company specializing in mobile apps, web development, AI, blockchain, and cybersecurity.",
      "We're a trusted partner for digital transformation with expertise across multiple technology domains.",
      "We provide comprehensive technology services to help businesses succeed digitally.",
    ],
    "company.team": [
      "Our team consists of experienced developers, designers, and specialists across all technology domains.",
      "We have a talented team with years of experience in their respective fields.",
      "Our team is composed of expert professionals passionate about innovative solutions.",
    ],
    "company.experience": [
      "We have years of industry experience with a proven track record of successful project delivery.",
      "Our team brings extensive combined experience in software development and technology consulting.",
      "We've successfully delivered hundreds of projects for clients globally.",
    ],

    // CONTACT
    "contact.information": [
      "You can reach us through our contact form, email, or phone. Visit our Contact page for details.",
      "We're here to help! Check our Contact page for communication channels. We respond within 24 hours.",
      "Feel free to contact us anytime via email, phone, or our online contact form.",
    ],
    "contact.support": [
      "Our support team is available to help with any questions or issues.",
      "We provide comprehensive support. Contact us through our support channels.",
      "We're here to support you! Reach out anytime for assistance.",
    ],

    // TIMELINE
    "timeline.inquiry": [
      "Project timelines vary based on complexity. Simple projects take weeks, complex ones take months. Let's discuss your needs.",
      "It depends on your requirements. We'll provide a detailed timeline after understanding your needs.",
      "We work on agile timelines. Share your requirements and we'll provide an estimate.",
    ],
    "timeline.urgent": [
      "We can accommodate urgent projects with dedicated resources and accelerated timelines.",
      "Yes! We handle urgent projects. Contact us with your deadline and requirements.",
      "We can work on expedited schedules. Share your deadline and project details.",
    ],

    // PORTFOLIO
    "portfolio.casestudies": [
      "Yes! We have case studies showcasing our work across mobile, web, AI, blockchain, and design.",
      "Absolutely! Visit our Case Studies section to see examples of our successful projects.",
      "We maintain a portfolio of successful projects demonstrating our expertise.",
    ],
    "portfolio.similar": [
      "Yes! We have experience with similar projects. Let's discuss your specific needs.",
      "Definitely! We've worked on comparable projects. Share your requirements.",
      "Absolutely! Our past experience positions us well to handle your needs.",
    ],

    // PARTNERSHIPS
    "partnership.inquiry": [
      "We're interested in exploring partnership opportunities! Share your proposal.",
      "Yes! We're open to partnerships and collaborations. Contact us with your idea.",
      "Absolutely! We believe in collaboration. Let's discuss partnership possibilities.",
    ],

    // PROCESS
    "process.workflow": [
      "We follow an agile process with discovery, design, development, testing, and deployment phases.",
      "Our process emphasizes collaboration and transparency with regular communication.",
      "We use industry best practices and agile methodology for quality and timely delivery.",
    ],
    "process.communication": [
      "We maintain regular communication through updates, stand-ups, and dedicated project managers.",
      "Communication is key! We provide regular updates and maintain open channels.",
      "We believe in transparent communication with regular status updates.",
    ],
    "process.revision": [
      "Yes, revisions are included. Specific limits depend on project scope.",
      "Absolutely! We work with you to refine the solution until you're satisfied.",
      "Yes! We include revisions to ensure the final product meets your expectations.",
    ],

    // TECHNOLOGY
    "tech.stack": [
      "We use modern stacks including React, Next.js, Node.js, Python, and cloud platforms.",
      "Our tech choices depend on your project needs. We select the best tools available.",
      "We work with cutting-edge technologies including React, Vue.js, Node.js, and AWS.",
    ],
    "tech.scalability": [
      "Yes! Scalability is built into our solutions using cloud infrastructure and best practices.",
      "Absolutely! We design applications to handle growth and high traffic.",
      "We design for scalability from the start using cloud-based architecture.",
    ],

    // MAINTENANCE
    "maintenance.support": [
      "Yes! We provide post-launch support including bug fixes, updates, and maintenance plans.",
      "Absolutely! We offer ongoing maintenance and support packages.",
      "We provide comprehensive post-launch support and maintenance services.",
    ],
    "maintenance.hosting": [
      "Yes! We handle hosting and deployment on cloud platforms like AWS and Azure.",
      "Absolutely! We can manage hosting and ensure high availability.",
      "We provide deployment and can manage your hosting infrastructure.",
    ],

    // TRAINING
    "training.needed": [
      "Yes! We provide training and documentation for your team.",
      "Absolutely! We include training and knowledge transfer in our services.",
      "We provide comprehensive training and documentation.",
    ],

    // CUSTOMIZATION
    "custom.requirements": [
      "Yes! Customization is our specialty. We build solutions for your specific needs.",
      "Absolutely! We specialize in custom development tailored to your requirements.",
      "Definitely! We customize everything to fit your exact needs.",
    ],

    // PAYMENT
    "payment.methods": [
      "We offer flexible payment methods and milestone-based payment plans.",
      "We accept multiple payment options and flexible payment schedules.",
      "We offer various payment options structured around project milestones.",
    ],

    // LEGAL
    "legal.terms": [
      "We provide clear terms and are happy to sign NDAs and custom agreements.",
      "Yes! We provide comprehensive terms and can sign NDAs.",
      "Absolutely! We maintain professional legal agreements and custom contracts.",
    ],
    "legal.compliance": [
      "We comply with GDPR, data protection, and industry-specific regulations.",
      "Yes! We follow data protection standards and industry compliance requirements.",
      "We maintain compliance with security standards and relevant regulations.",
    ],

    // JOBS
    "jobs.inquiry": [
      "We're always looking for talented professionals! Check our careers page for open positions.",
      "Yes! We hire talented developers and designers. Check our careers section.",
      "Absolutely! Submit your profile and we'll review opportunities for you.",
    ],

    // FAQ
    "faq.difference": [
      "We stand out through expertise, quality focus, transparent communication, and innovative solutions.",
      "Our advantages include experienced team, diverse services, proven track record, and client focus.",
      "We differentiate through expert team, comprehensive services, and long-term client relationships.",
    ],
    "faq.quality": [
      "We ensure quality through rigorous testing, code reviews, and adherence to best practices.",
      "Quality is paramount. We follow strict QA processes and comprehensive testing.",
      "We maintain quality through automated testing, code reviews, and best practices.",
    ],
    "faq.guarantee": [
      "We stand behind our work with quality assurance and continuous support.",
      "We guarantee quality and reliability. If you're not satisfied, we'll make it right.",
      "Absolutely! We're confident in our quality and provide ongoing support.",
    ],
  },
};
